GET http://localhost:3003/api/blogs


### 
GET http://localhost:3003/api/blogs/5a422a851b54a676234d17f7


###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "String1",
    "author": "String2",
    "url": "String3",
    "likes": 10

}


