GET http://localhost:3003/api/blogs


### 
GET http://localhost:3003/api/blogs/63d9a2fa604ddc5caa69ff18


###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "String12",
    "author": "String23",
    "url": "String4",
    "likes": 10

}

###
DELETE http://localhost:3003/api/blogs/63ddbb8deafd84d72a7fa317
